# Generated by Django 5.1.5 on 2025-04-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='likes',
        ),
        migrations.AddField(
            model_name='answers',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
